<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Repository to Slackware64 Current by Conraid">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Conraid Repository</title>
<meta property="og:site_name" content="conraid">
<meta property="og:locale" content="it_IT">
<meta property="og:url" content="http://slack.conraid.net">
<meta property="og:title" content='Slackers'>
<meta property="og:description" content="Visita il sito di Corrado Franco">
<meta property="og:image" content="http://slack.conraid.net/images/avatar.jpg">
<meta property="og:type" content="aboutme_prod:page">
<meta property="fb:app_id" content="568492989985060">
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@Slackers_it">
<meta name="twitter:title" content='Slackers'>
<meta name="twitter:description" content="Visita il sito di Corrado Franco">
<meta name="twitter:image" content="http://slack.conraid.net/images/avatar.jpg">
<meta name="twitter:image:width" content="520">
<meta name="twitter:image:height" content="520">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">  
<link rel="canonical" href="http://slack.conraid.net/index.php">
</head>
<body>
<header>
<h1>Repository for Slackware64 current</h1>
</header>

<section>
<p>Packages are in <a href="/repository" title="This repository">this repository</a>.</p>
<p>SlackBuilds are on <a href="https://github.com/conraid/SlackBuilds/" title="" rel="noopener external" target="blank">GitHub</a>.</p>

<div class="repository">

<ul>
<li>abook:&nbsp;&nbsp;&nbsp;0.6.1</li>
<li>accounts-qml-module:&nbsp;&nbsp;&nbsp;0.7</li>
<li>acme_sh:&nbsp;&nbsp;&nbsp;3.0.2</li>
<li>acpiclient:&nbsp;&nbsp;&nbsp;1.7</li>
<li>acpitool:&nbsp;&nbsp;&nbsp;0.5.1</li>
<li>adns:&nbsp;&nbsp;&nbsp;1.6.0</li>
<li>advancecomp:&nbsp;&nbsp;&nbsp;2.1</li>
<li>afflib:&nbsp;&nbsp;&nbsp;3.7.19</li>
<li>afl:&nbsp;&nbsp;&nbsp;2.57b</li>
<li>afl-utils:&nbsp;&nbsp;&nbsp;1.35a</li>
<li>aide:&nbsp;&nbsp;&nbsp;0.17.4</li>
<li>aircrack-ng:&nbsp;&nbsp;&nbsp;1.6</li>
<li>akira:&nbsp;&nbsp;&nbsp;0.0.16</li>
<li>alabaster:&nbsp;&nbsp;&nbsp;0.7.12</li>
<li>alien:&nbsp;&nbsp;&nbsp;8.95</li>
<li>amule:&nbsp;&nbsp;&nbsp;2.3.3</li>
<li>ansifilter:&nbsp;&nbsp;&nbsp;2.18</li>
<li>antiword:&nbsp;&nbsp;&nbsp;0.37</li>
<li>apachetop:&nbsp;&nbsp;&nbsp;0.19.7</li>
<li>apngasm:&nbsp;&nbsp;&nbsp;3.1.10</li>
<li>apngdis:&nbsp;&nbsp;&nbsp;2.9</li>
<li>appstream-glib:&nbsp;&nbsp;&nbsp;0.7.18</li>
<li>apt-mirror:&nbsp;&nbsp;&nbsp;0.5.4</li>
<li>argbash:&nbsp;&nbsp;&nbsp;2.10.0</li>
<li>aria2:&nbsp;&nbsp;&nbsp;1.36.0</li>
<li>arp-scan:&nbsp;&nbsp;&nbsp;1.9.7</li>
<li>arpalert:&nbsp;&nbsp;&nbsp;2.0.12</li>
<li>arptables:&nbsp;&nbsp;&nbsp;0.0.5</li>
<li>arpwatch:&nbsp;&nbsp;&nbsp;3.3</li>
<li>asn1crypto:&nbsp;&nbsp;&nbsp;1.5.1</li>
<li>atom-bin:&nbsp;&nbsp;&nbsp;1.60.0</li>
<li>atool:&nbsp;&nbsp;&nbsp;0.39.0</li>
<li>atop:&nbsp;&nbsp;&nbsp;2.7.1</li>
<li>audit:&nbsp;&nbsp;&nbsp;3.0.8</li>
<li>authoscope:&nbsp;&nbsp;&nbsp;0.8.1</li>
<li>autossh:&nbsp;&nbsp;&nbsp;1.4g</li>
<li>avahi:&nbsp;&nbsp;&nbsp;0.8</li>
<li>aws-cli:&nbsp;&nbsp;&nbsp;1.22.84</li>
<li>awscrt:&nbsp;&nbsp;&nbsp;0.13.6</li>
<li>babel-loader:&nbsp;&nbsp;&nbsp;8.2.4</li>
<li>balsa:&nbsp;&nbsp;&nbsp;2.6.3</li>
<li>bash-language-server:&nbsp;&nbsp;&nbsp;2.0.0</li>
<li>bashdb:&nbsp;&nbsp;&nbsp;5.0_1.1.2</li>
<li>bashstyle-ng:&nbsp;&nbsp;&nbsp;10.7.3</li>
<li>bashtop:&nbsp;&nbsp;&nbsp;0.9.25</li>
<li>beautifulsoup4:&nbsp;&nbsp;&nbsp;4.10.0</li>
<li>bettercap:&nbsp;&nbsp;&nbsp;2.32.0</li>
<li>bindfs:&nbsp;&nbsp;&nbsp;1.15.1</li>
<li>binwalk:&nbsp;&nbsp;&nbsp;2.3.3</li>
<li>birdfont:&nbsp;&nbsp;&nbsp;2.30.0</li>
<li>birdtray:&nbsp;&nbsp;&nbsp;1.9.0</li>
<li>bleachbit:&nbsp;&nbsp;&nbsp;4.4.2</li>
<li>bluefish:&nbsp;&nbsp;&nbsp;2.2.12</li>
<li>bmon:&nbsp;&nbsp;&nbsp;4.0</li>
<li>bonnie++:&nbsp;&nbsp;&nbsp;2.00a</li>
<li>bootlint:&nbsp;&nbsp;&nbsp;1.1.0</li>
<li>botan:&nbsp;&nbsp;&nbsp;2.19.1</li>
<li>bourbon:&nbsp;&nbsp;&nbsp;7.2.0</li>
<li>bpytop:&nbsp;&nbsp;&nbsp;1.0.68</li>
<li>browser-sync:&nbsp;&nbsp;&nbsp;2.27.9</li>
<li>browsertime:&nbsp;&nbsp;&nbsp;15.3.0</li>
<li>bubblewrap:&nbsp;&nbsp;&nbsp;0.6.1</li>
<li>bully:&nbsp;&nbsp;&nbsp;3ab3bc8</li>
<li>bup:&nbsp;&nbsp;&nbsp;0.32</li>
<li>bwm-ng:&nbsp;&nbsp;&nbsp;0.6.3</li>
<li>bwping:&nbsp;&nbsp;&nbsp;2.5</li>
<li>byacc:&nbsp;&nbsp;&nbsp;20220128</li>
<li>cabextract:&nbsp;&nbsp;&nbsp;1.9.1</li>
<li>cachetools:&nbsp;&nbsp;&nbsp;5.0.0</li>
<li>cadence:&nbsp;&nbsp;&nbsp;0.9.1</li>
<li>cairocffi:&nbsp;&nbsp;&nbsp;1.3.0</li>
<li>cairosvg:&nbsp;&nbsp;&nbsp;2.5.2</li>
<li>ccid:&nbsp;&nbsp;&nbsp;1.5.0</li>
<li>celt051:&nbsp;&nbsp;&nbsp;0.5.1.3</li>
<li>cfpeek:&nbsp;&nbsp;&nbsp;1.2</li>
<li>checkbashisms:&nbsp;&nbsp;&nbsp;2.22.1</li>
<li>checkit:&nbsp;&nbsp;&nbsp;0.5.0</li>
<li>checksec:&nbsp;&nbsp;&nbsp;2.5.0</li>
<li>chkrootkit:&nbsp;&nbsp;&nbsp;0.55</li>
<li>chump:&nbsp;&nbsp;&nbsp;1.6.0</li>
<li>cimg:&nbsp;&nbsp;&nbsp;3.0.2</li>
<li>clamav:&nbsp;&nbsp;&nbsp;0.104.2</li>
<li>cld2:&nbsp;&nbsp;&nbsp;20150820_git</li>
<li>click:&nbsp;&nbsp;&nbsp;8.1.0</li>
<li>cmark:&nbsp;&nbsp;&nbsp;0.30.2</li>
<li>cmus:&nbsp;&nbsp;&nbsp;2.9.1</li>
<li>coffeescript:&nbsp;&nbsp;&nbsp;2.6.1</li>
<li>collectd:&nbsp;&nbsp;&nbsp;5.12.0</li>
<li>colorama:&nbsp;&nbsp;&nbsp;0.4.4</li>
<li>colordiff:&nbsp;&nbsp;&nbsp;1.0.20</li>
<li>communism:&nbsp;&nbsp;&nbsp;0.1.0</li>
<li>configobj:&nbsp;&nbsp;&nbsp;5.0.6</li>
<li>confuse:&nbsp;&nbsp;&nbsp;3.3</li>
<li>containerd:&nbsp;&nbsp;&nbsp;1.6.2</li>
<li>converseen:&nbsp;&nbsp;&nbsp;0.9.9.4</li>
<li>cpprestsdk:&nbsp;&nbsp;&nbsp;2.10.18</li>
<li>cppunit:&nbsp;&nbsp;&nbsp;1.15.1</li>
<li>cpuid:&nbsp;&nbsp;&nbsp;20220224</li>
<li>cpuid2cpuflags:&nbsp;&nbsp;&nbsp;11</li>
<li>crlfuzz:&nbsp;&nbsp;&nbsp;1.4.1</li>
<li>cryptography:&nbsp;&nbsp;&nbsp;36.0.2</li>
<li>csscss:&nbsp;&nbsp;&nbsp;bac3e42</li>
<li>csso:&nbsp;&nbsp;&nbsp;5.0.3</li>
<li>csso-cli:&nbsp;&nbsp;&nbsp;3.0.0</li>
<li>cssselect2:&nbsp;&nbsp;&nbsp;0.5.0</li>
<li>cssunminifier:&nbsp;&nbsp;&nbsp;0.0.2</li>
<li>ctunnel:&nbsp;&nbsp;&nbsp;0.8</li>
<li>cunit:&nbsp;&nbsp;&nbsp;2.1_3</li>
<li>darkhttpd:&nbsp;&nbsp;&nbsp;1.13</li>
<li>darkstat:&nbsp;&nbsp;&nbsp;3.0.721</li>
<li>darktable:&nbsp;&nbsp;&nbsp;3.8.1</li>
<li>dart-sass-bin:&nbsp;&nbsp;&nbsp;1.49.9</li>
<li>dcfldd:&nbsp;&nbsp;&nbsp;1.3.4_1</li>
<li>decorator:&nbsp;&nbsp;&nbsp;5.1.1</li>
<li>defusedxml:&nbsp;&nbsp;&nbsp;0.7.1</li>
<li>dep:&nbsp;&nbsp;&nbsp;0.5.4</li>
<li>detox:&nbsp;&nbsp;&nbsp;1.4.5</li>
<li>device-tree-compiler:&nbsp;&nbsp;&nbsp;1.6.1</li>
<li>dia:&nbsp;&nbsp;&nbsp;0.97.3</li>
<li>diskmonitor:&nbsp;&nbsp;&nbsp;0.3.4</li>
<li>diskscan:&nbsp;&nbsp;&nbsp;0.20</li>
<li>distorm:&nbsp;&nbsp;&nbsp;3.5.2b</li>
<li>dkms:&nbsp;&nbsp;&nbsp;3.0.3</li>
<li>dnsperf:&nbsp;&nbsp;&nbsp;2.9.0</li>
<li>dnsscan:&nbsp;&nbsp;&nbsp;1.0</li>
<li>dnstracer:&nbsp;&nbsp;&nbsp;1.10</li>
<li>dos2unix:&nbsp;&nbsp;&nbsp;7.4.2</li>
<li>double-conversion:&nbsp;&nbsp;&nbsp;3.2.0</li>
<li>dpkg:&nbsp;&nbsp;&nbsp;1.21.6</li>
<li>dropbox-bin:&nbsp;&nbsp;&nbsp;144.4.4491</li>
<li>dwdiff:&nbsp;&nbsp;&nbsp;2.1.4</li>
<li>ecryptfs-simple:&nbsp;&nbsp;&nbsp;2016.11.16.1</li>
<li>ecryptfs-utils:&nbsp;&nbsp;&nbsp;111</li>
<li>encfs:&nbsp;&nbsp;&nbsp;1.9.5</li>
<li>etcher-bin:&nbsp;&nbsp;&nbsp;1.7.8</li>
<li>ettercap:&nbsp;&nbsp;&nbsp;0.8.3.1</li>
<li>evtest:&nbsp;&nbsp;&nbsp;1.34</li>
<li>exempi:&nbsp;&nbsp;&nbsp;2.6.1</li>
<li>exiftool:&nbsp;&nbsp;&nbsp;12.40</li>
<li>exploitdb:&nbsp;&nbsp;&nbsp;20220324</li>
<li>eyed3:&nbsp;&nbsp;&nbsp;0.9.6</li>
<li>faac:&nbsp;&nbsp;&nbsp;1_30</li>
<li>faad2:&nbsp;&nbsp;&nbsp;2.10.0</li>
<li>fail2ban:&nbsp;&nbsp;&nbsp;5093ff8</li>
<li>faudio:&nbsp;&nbsp;&nbsp;22.02</li>
<li>fdupes:&nbsp;&nbsp;&nbsp;2.1.2</li>
<li>ferm:&nbsp;&nbsp;&nbsp;2.6</li>
<li>figlet:&nbsp;&nbsp;&nbsp;2.2.5</li>
<li>filezilla:&nbsp;&nbsp;&nbsp;3.58.0</li>
<li>findomain:&nbsp;&nbsp;&nbsp;7.0.1</li>
<li>firewalld:&nbsp;&nbsp;&nbsp;1.1.1</li>
<li>flameshot:&nbsp;&nbsp;&nbsp;11.0.0</li>
<li>flatbuffers:&nbsp;&nbsp;&nbsp;2.0.0</li>
<li>flickcurl:&nbsp;&nbsp;&nbsp;1.26</li>
<li>fontforge:&nbsp;&nbsp;&nbsp;20220308</li>
<li>forkstat:&nbsp;&nbsp;&nbsp;0.02.17</li>
<li>fping:&nbsp;&nbsp;&nbsp;5.1</li>
<li>fuseiso:&nbsp;&nbsp;&nbsp;20070708</li>
<li>fwknop:&nbsp;&nbsp;&nbsp;2.6.11_pre1</li>
<li>gcab:&nbsp;&nbsp;&nbsp;1.4</li>
<li>gdata-python-client:&nbsp;&nbsp;&nbsp;3541dfa_git</li>
<li>gdl:&nbsp;&nbsp;&nbsp;3.40.0</li>
<li>gengetopt:&nbsp;&nbsp;&nbsp;2.23</li>
<li>geoip:&nbsp;&nbsp;&nbsp;1.6.12</li>
<li>geoipupdate:&nbsp;&nbsp;&nbsp;4.9.0</li>
<li>ghostwriter:&nbsp;&nbsp;&nbsp;2.1.2</li>
<li>gif2apng:&nbsp;&nbsp;&nbsp;1.9</li>
<li>gif2png:&nbsp;&nbsp;&nbsp;3.0.0</li>
<li>gifsicle:&nbsp;&nbsp;&nbsp;1.93</li>
<li>gimagereader:&nbsp;&nbsp;&nbsp;3.4.0</li>
<li>gimp-elsamuko:&nbsp;&nbsp;&nbsp;9a34874</li>
<li>gimp-lensfun:&nbsp;&nbsp;&nbsp;0.2.4</li>
<li>gimp-lqr-plugin:&nbsp;&nbsp;&nbsp;ae0ecb4</li>
<li>gimp-plugin-export-layers:&nbsp;&nbsp;&nbsp;3.3.1</li>
<li>gimp-script-fu:&nbsp;&nbsp;&nbsp;51</li>
<li>gimp-separate+:&nbsp;&nbsp;&nbsp;0.5.8</li>
<li>gimp3:&nbsp;&nbsp;&nbsp;2.99.10</li>
<li>gimp_instagram_effects:&nbsp;&nbsp;&nbsp;0.1</li>
<li>git-ftp:&nbsp;&nbsp;&nbsp;1.6.0</li>
<li>git-run:&nbsp;&nbsp;&nbsp;0.5.5</li>
<li>gitdb:&nbsp;&nbsp;&nbsp;4.0.9</li>
<li>github-cli:&nbsp;&nbsp;&nbsp;2.6.0</li>
<li>gitkraken-bin:&nbsp;&nbsp;&nbsp;8.3.3</li>
<li>gitpython:&nbsp;&nbsp;&nbsp;3.1.27</li>
<li>gitqlient:&nbsp;&nbsp;&nbsp;1.4.3</li>
<li>glade:&nbsp;&nbsp;&nbsp;3.38.2</li>
<li>gmic:&nbsp;&nbsp;&nbsp;3.0.2</li>
<li>gnuit:&nbsp;&nbsp;&nbsp;4.9.5</li>
<li>go:&nbsp;&nbsp;&nbsp;1.18</li>
<li>go-crypto:&nbsp;&nbsp;&nbsp;38f3c27</li>
<li>go-md2man:&nbsp;&nbsp;&nbsp;2.0.1</li>
<li>go-net:&nbsp;&nbsp;&nbsp;27dd868</li>
<li>go-sys:&nbsp;&nbsp;&nbsp;95c6836</li>
<li>goaccess:&nbsp;&nbsp;&nbsp;1.5.6</li>
<li>goobook:&nbsp;&nbsp;&nbsp;3.5.1</li>
<li>goocanvas:&nbsp;&nbsp;&nbsp;3.0.0</li>
<li>google-api-core:&nbsp;&nbsp;&nbsp;2.7.1</li>
<li>google-api-python-client:&nbsp;&nbsp;&nbsp;2.42.0</li>
<li>google-auth:&nbsp;&nbsp;&nbsp;2.6.2</li>
<li>google-auth-httplib2:&nbsp;&nbsp;&nbsp;0.1.0</li>
<li>google-webdesigner-bin:&nbsp;&nbsp;&nbsp;12.0.0.0719_1</li>
<li>googleapis-common-protos:&nbsp;&nbsp;&nbsp;1.56.0</li>
<li>gping:&nbsp;&nbsp;&nbsp;1.2.6</li>
<li>granite:&nbsp;&nbsp;&nbsp;6.2.0</li>
<li>graphicsmagick:&nbsp;&nbsp;&nbsp;1.3.38</li>
<li>graphviz:&nbsp;&nbsp;&nbsp;3.0.0</li>
<li>greenlet:&nbsp;&nbsp;&nbsp;1.1.2</li>
<li>grunt-cli:&nbsp;&nbsp;&nbsp;1.4.3</li>
<li>gsm:&nbsp;&nbsp;&nbsp;1.0.19</li>
<li>gsmartcontrol:&nbsp;&nbsp;&nbsp;1.1.4</li>
<li>gst-plugins-ugly:&nbsp;&nbsp;&nbsp;1.20.1</li>
<li>gstreamermm:&nbsp;&nbsp;&nbsp;1.10.0</li>
<li>gtk-vnc:&nbsp;&nbsp;&nbsp;1.3.0</li>
<li>gtkimageview:&nbsp;&nbsp;&nbsp;1.6.4</li>
<li>gtksourceview4:&nbsp;&nbsp;&nbsp;4.8.3</li>
<li>gtkspell3:&nbsp;&nbsp;&nbsp;3.0.10</li>
<li>gtop:&nbsp;&nbsp;&nbsp;1.1.3</li>
<li>gts:&nbsp;&nbsp;&nbsp;0.7.6</li>
<li>guetzli:&nbsp;&nbsp;&nbsp;1.0.1</li>
<li>gulp:&nbsp;&nbsp;&nbsp;4.0.2</li>
<li>handbrake:&nbsp;&nbsp;&nbsp;1.3.3</li>
<li>hardening-check:&nbsp;&nbsp;&nbsp;2.22.1</li>
<li>hashcat:&nbsp;&nbsp;&nbsp;6.2.5</li>
<li>hashcat-utils:&nbsp;&nbsp;&nbsp;1.9</li>
<li>helix-editor:&nbsp;&nbsp;&nbsp;22.03</li>
<li>hexedit:&nbsp;&nbsp;&nbsp;1.5</li>
<li>hiredis:&nbsp;&nbsp;&nbsp;1.0.2</li>
<li>hping:&nbsp;&nbsp;&nbsp;3.0.0_git</li>
<li>hstr:&nbsp;&nbsp;&nbsp;2.5</li>
<li>html-minifier:&nbsp;&nbsp;&nbsp;4.0.0</li>
<li>html5lib-python:&nbsp;&nbsp;&nbsp;1.1</li>
<li>htmlhint:&nbsp;&nbsp;&nbsp;1.1.3</li>
<li>http-parser:&nbsp;&nbsp;&nbsp;2.9.4</li>
<li>httperf:&nbsp;&nbsp;&nbsp;de8cd6a</li>
<li>httpie:&nbsp;&nbsp;&nbsp;3.1.0</li>
<li>httping:&nbsp;&nbsp;&nbsp;2.5</li>
<li>httplib2:&nbsp;&nbsp;&nbsp;0.20.4</li>
<li>httpry:&nbsp;&nbsp;&nbsp;0.1.8</li>
<li>httrack:&nbsp;&nbsp;&nbsp;3.49.2</li>
<li>httraqt:&nbsp;&nbsp;&nbsp;1.4.9</li>
<li>hugo-bin:&nbsp;&nbsp;&nbsp;0.96.0</li>
<li>hungrycat:&nbsp;&nbsp;&nbsp;0.4.1</li>
<li>hunspell-it:&nbsp;&nbsp;&nbsp;2.4</li>
<li>hwinfo:&nbsp;&nbsp;&nbsp;21.80</li>
<li>hwloc:&nbsp;&nbsp;&nbsp;2.3.0</li>
<li>hydra:&nbsp;&nbsp;&nbsp;9.3</li>
<li>hydroxide:&nbsp;&nbsp;&nbsp;0.2.21</li>
<li>hyperscan:&nbsp;&nbsp;&nbsp;5.4.0</li>
<li>i2util:&nbsp;&nbsp;&nbsp;4.4.3</li>
<li>icdiff:&nbsp;&nbsp;&nbsp;2.0.4</li>
<li>icoutils:&nbsp;&nbsp;&nbsp;0.32.3</li>
<li>id3:&nbsp;&nbsp;&nbsp;0.80</li>
<li>ike-scan:&nbsp;&nbsp;&nbsp;1.9.5</li>
<li>imagesize:&nbsp;&nbsp;&nbsp;1.3.0</li>
<li>img2pdf:&nbsp;&nbsp;&nbsp;0.4.3</li>
<li>imlib2:&nbsp;&nbsp;&nbsp;1.8.1</li>
<li>inkscape:&nbsp;&nbsp;&nbsp;1.1.1</li>
<li>innotop:&nbsp;&nbsp;&nbsp;1.13.0</li>
<li>instant-markdown:&nbsp;&nbsp;&nbsp;1.0.0</li>
<li>intel-microcode:&nbsp;&nbsp;&nbsp;20220207</li>
<li>ioping:&nbsp;&nbsp;&nbsp;1.2</li>
<li>iotop:&nbsp;&nbsp;&nbsp;0.6</li>
<li>iperf2:&nbsp;&nbsp;&nbsp;2.1.6</li>
<li>iperf3:&nbsp;&nbsp;&nbsp;3.11</li>
<li>ipguard:&nbsp;&nbsp;&nbsp;1.04</li>
<li>ipscan-bin:&nbsp;&nbsp;&nbsp;3.8.2</li>
<li>iptstate:&nbsp;&nbsp;&nbsp;2.2.7</li>
<li>isomaster:&nbsp;&nbsp;&nbsp;1.3.16</li>
<li>iucode-tool:&nbsp;&nbsp;&nbsp;2.3.1</li>
<li>jack:&nbsp;&nbsp;&nbsp;1.9.20</li>
<li>jasmine-node:&nbsp;&nbsp;&nbsp;3.0.0</li>
<li>jdk:&nbsp;&nbsp;&nbsp;18</li>
<li>jhead:&nbsp;&nbsp;&nbsp;3.04</li>
<li>john:&nbsp;&nbsp;&nbsp;1.9.0_jumbo_1</li>
<li>jpegoptim:&nbsp;&nbsp;&nbsp;1.4.6</li>
<li>jq:&nbsp;&nbsp;&nbsp;1.6</li>
<li>js-beautify:&nbsp;&nbsp;&nbsp;1.14.2</li>
<li>json-c-static:&nbsp;&nbsp;&nbsp;0.15_20200726</li>
<li>jsoncpp:&nbsp;&nbsp;&nbsp;1.9.5</li>
<li>kaccounts-integration:&nbsp;&nbsp;&nbsp;21.12.3</li>
<li>kaccounts-providers:&nbsp;&nbsp;&nbsp;21.12.3</li>
<li>kcolorpicker:&nbsp;&nbsp;&nbsp;0.1.6</li>
<li>kdiff3:&nbsp;&nbsp;&nbsp;1.9.5</li>
<li>keepassxc:&nbsp;&nbsp;&nbsp;2.7.0</li>
<li>keybase-bin:&nbsp;&nbsp;&nbsp;5.9.3</li>
<li>keychain:&nbsp;&nbsp;&nbsp;2.8.5</li>
<li>kimageannotator:&nbsp;&nbsp;&nbsp;0.5.3</li>
<li>kismet:&nbsp;&nbsp;&nbsp;2022_02_R1</li>
<li>known_hosts:&nbsp;&nbsp;&nbsp;1.0.0</li>
<li>kquickimageeditor:&nbsp;&nbsp;&nbsp;0.2.0</li>
<li>ksnip:&nbsp;&nbsp;&nbsp;1.9.2</li>
<li>kyotocabinet:&nbsp;&nbsp;&nbsp;1.2.79</li>
<li>ladspa_sdk:&nbsp;&nbsp;&nbsp;1.17</li>
<li>lastpass-cli:&nbsp;&nbsp;&nbsp;1.3.3</li>
<li>leptonica:&nbsp;&nbsp;&nbsp;1.82.0</li>
<li>lerna:&nbsp;&nbsp;&nbsp;4.0.0</li>
<li>lfs:&nbsp;&nbsp;&nbsp;2.5.0</li>
<li>libaccounts-glib:&nbsp;&nbsp;&nbsp;1.25</li>
<li>libaccounts-qt:&nbsp;&nbsp;&nbsp;1.16</li>
<li>libasecnsp11:&nbsp;&nbsp;&nbsp;1</li>
<li>libass:&nbsp;&nbsp;&nbsp;0.15.1</li>
<li>libb64:&nbsp;&nbsp;&nbsp;2.0.0.1</li>
<li>libbfio:&nbsp;&nbsp;&nbsp;20220120</li>
<li>libbsd:&nbsp;&nbsp;&nbsp;0.11.5</li>
<li>libcacard:&nbsp;&nbsp;&nbsp;2.8.1</li>
<li>libcdr:&nbsp;&nbsp;&nbsp;0.1.7</li>
<li>libck:&nbsp;&nbsp;&nbsp;0.7.1</li>
<li>libcli:&nbsp;&nbsp;&nbsp;1.10.7</li>
<li>libconfig:&nbsp;&nbsp;&nbsp;1.7.3</li>
<li>libcsv:&nbsp;&nbsp;&nbsp;3.0.3</li>
<li>libcurl-gnutls:&nbsp;&nbsp;&nbsp;7.82.0</li>
<li>libdaemon:&nbsp;&nbsp;&nbsp;0.14</li>
<li>libdbi:&nbsp;&nbsp;&nbsp;0.9.0</li>
<li>libdbi-drivers:&nbsp;&nbsp;&nbsp;0.9.0</li>
<li>libdc1394:&nbsp;&nbsp;&nbsp;2.2.6</li>
<li>libde265:&nbsp;&nbsp;&nbsp;1.0.8</li>
<li>libdnet:&nbsp;&nbsp;&nbsp;1.14</li>
<li>libesmtp:&nbsp;&nbsp;&nbsp;1.1.0</li>
<li>libev:&nbsp;&nbsp;&nbsp;4.33</li>
<li>libewf:&nbsp;&nbsp;&nbsp;20150126</li>
<li>libfdk-aac:&nbsp;&nbsp;&nbsp;2.0.2</li>
<li>libfilezilla:&nbsp;&nbsp;&nbsp;0.36.0</li>
<li>libgovirt:&nbsp;&nbsp;&nbsp;0.3.8</li>
<li>libgsasl:&nbsp;&nbsp;&nbsp;1.10.0</li>
<li>libhandy:&nbsp;&nbsp;&nbsp;1.2.2</li>
<li>libheif:&nbsp;&nbsp;&nbsp;1.12.0</li>
<li>libhtp:&nbsp;&nbsp;&nbsp;0.5.39</li>
<li>libiptcdata:&nbsp;&nbsp;&nbsp;1.0.5</li>
<li>libircclient:&nbsp;&nbsp;&nbsp;1.10</li>
<li>liblqr:&nbsp;&nbsp;&nbsp;0.4.2</li>
<li>libmanette:&nbsp;&nbsp;&nbsp;0.2.6</li>
<li>libmaxminddb:&nbsp;&nbsp;&nbsp;1.6.0</li>
<li>libmd:&nbsp;&nbsp;&nbsp;1.0.4</li>
<li>libmediainfo:&nbsp;&nbsp;&nbsp;21.09</li>
<li>libmemcached:&nbsp;&nbsp;&nbsp;1.0.18</li>
<li>libmesode:&nbsp;&nbsp;&nbsp;0.10.1</li>
<li>libmicrohttpd:&nbsp;&nbsp;&nbsp;0.9.75</li>
<li>libminizip:&nbsp;&nbsp;&nbsp;1.2.12</li>
<li>libmodsecurity:&nbsp;&nbsp;&nbsp;3.0.6</li>
<li>libmp3splt:&nbsp;&nbsp;&nbsp;0.9.2</li>
<li>libmp4v2:&nbsp;&nbsp;&nbsp;5.0.1</li>
<li>libmpack:&nbsp;&nbsp;&nbsp;1.0.5</li>
<li>libmpeg2:&nbsp;&nbsp;&nbsp;0.5.1</li>
<li>libnet:&nbsp;&nbsp;&nbsp;1.2</li>
<li>libnfs:&nbsp;&nbsp;&nbsp;5.0.1</li>
<li>libnids:&nbsp;&nbsp;&nbsp;1.26</li>
<li>libopenshot:&nbsp;&nbsp;&nbsp;0.2.7</li>
<li>libopenshot-audio:&nbsp;&nbsp;&nbsp;0.2.2</li>
<li>liboping:&nbsp;&nbsp;&nbsp;1.10.0</li>
<li>libosinfo:&nbsp;&nbsp;&nbsp;1.10.0</li>
<li>libotr:&nbsp;&nbsp;&nbsp;4.1.1</li>
<li>libqpsd:&nbsp;&nbsp;&nbsp;2.2.1</li>
<li>libquotient:&nbsp;&nbsp;&nbsp;0.6.11</li>
<li>libsafec:&nbsp;&nbsp;&nbsp;3.7.1</li>
<li>libsmi:&nbsp;&nbsp;&nbsp;0.5.0</li>
<li>libspiro:&nbsp;&nbsp;&nbsp;0.5.20150702</li>
<li>libstatgrab:&nbsp;&nbsp;&nbsp;0.92.1</li>
<li>libtermkey:&nbsp;&nbsp;&nbsp;b7fe3af_git</li>
<li>libtorrent:&nbsp;&nbsp;&nbsp;0.13.8</li>
<li>libtorrent-rasterbar:&nbsp;&nbsp;&nbsp;2.0.5</li>
<li>libtrash:&nbsp;&nbsp;&nbsp;3.7</li>
<li>libuninameslist:&nbsp;&nbsp;&nbsp;20211114</li>
<li>libupnp:&nbsp;&nbsp;&nbsp;1.14.12</li>
<li>liburcu:&nbsp;&nbsp;&nbsp;0.13.1</li>
<li>libvirt:&nbsp;&nbsp;&nbsp;8.1.0</li>
<li>libvirt-glib:&nbsp;&nbsp;&nbsp;4.0.0</li>
<li>libvirt-python:&nbsp;&nbsp;&nbsp;8.1.0</li>
<li>libvterm:&nbsp;&nbsp;&nbsp;1aa95e2</li>
<li>libwebsockets:&nbsp;&nbsp;&nbsp;4.3.1</li>
<li>libwpe:&nbsp;&nbsp;&nbsp;1.12.0</li>
<li>libx86emu:&nbsp;&nbsp;&nbsp;3.5</li>
<li>libxml++:&nbsp;&nbsp;&nbsp;2.42.1</li>
<li>libxmlbird:&nbsp;&nbsp;&nbsp;1.2.12</li>
<li>libzen:&nbsp;&nbsp;&nbsp;0.4.39</li>
<li>lifstat:&nbsp;&nbsp;&nbsp;20100318</li>
<li>lighttpd:&nbsp;&nbsp;&nbsp;1.4.64</li>
<li>linssid:&nbsp;&nbsp;&nbsp;3.6</li>
<li>lnav:&nbsp;&nbsp;&nbsp;0.10.1</li>
<li>logwatch:&nbsp;&nbsp;&nbsp;7.6</li>
<li>lsb-release:&nbsp;&nbsp;&nbsp;1.4</li>
<li>lshw:&nbsp;&nbsp;&nbsp;B.02.19.2</li>
<li>lterm:&nbsp;&nbsp;&nbsp;1.5.1</li>
<li>lua:&nbsp;&nbsp;&nbsp;5.4.4</li>
<li>lua-lpeg:&nbsp;&nbsp;&nbsp;1.0.2</li>
<li>lua-mpack:&nbsp;&nbsp;&nbsp;1.0.9</li>
<li>lua51:&nbsp;&nbsp;&nbsp;5.1.5</li>
<li>lua52:&nbsp;&nbsp;&nbsp;5.2.4</li>
<li>lua53:&nbsp;&nbsp;&nbsp;5.3.6</li>
<li>luajit:&nbsp;&nbsp;&nbsp;2.0.5</li>
<li>luarocks:&nbsp;&nbsp;&nbsp;3.8.0</li>
<li>luceneplusplus:&nbsp;&nbsp;&nbsp;3.0.8</li>
<li>luminance-hdr:&nbsp;&nbsp;&nbsp;2.6.0</li>
<li>luv:&nbsp;&nbsp;&nbsp;1.43.0_0</li>
<li>lwatch:&nbsp;&nbsp;&nbsp;0.6.2</li>
<li>lxappearance:&nbsp;&nbsp;&nbsp;0.6.3</li>
<li>lxml:&nbsp;&nbsp;&nbsp;4.8.0</li>
<li>lynis:&nbsp;&nbsp;&nbsp;3.0.7</li>
<li>lyx:&nbsp;&nbsp;&nbsp;2.3.6.1</li>
<li>macchanger:&nbsp;&nbsp;&nbsp;1.7.0</li>
<li>maldet:&nbsp;&nbsp;&nbsp;1.6.4</li>
<li>man-pages-it:&nbsp;&nbsp;&nbsp;5.06</li>
<li>masscan:&nbsp;&nbsp;&nbsp;1.3.2</li>
<li>mbedtls:&nbsp;&nbsp;&nbsp;2.28.0</li>
<li>md5deep:&nbsp;&nbsp;&nbsp;4.4</li>
<li>memcached:&nbsp;&nbsp;&nbsp;1.6.15</li>
<li>minidb:&nbsp;&nbsp;&nbsp;2.0.6</li>
<li>minimalcss:&nbsp;&nbsp;&nbsp;0.11.3</li>
<li>mjpegtools:&nbsp;&nbsp;&nbsp;2.2.1</li>
<li>mkvtoolnix:&nbsp;&nbsp;&nbsp;66.0.0</li>
<li>mm-common:&nbsp;&nbsp;&nbsp;1.0.4</li>
<li>modsecurity-apache:&nbsp;&nbsp;&nbsp;0.0.9_beta1</li>
<li>modsecurity-nginx:&nbsp;&nbsp;&nbsp;1.0.2</li>
<li>mongo-c-driver:&nbsp;&nbsp;&nbsp;1.21.0</li>
<li>monit:&nbsp;&nbsp;&nbsp;5.32.0</li>
<li>mosh:&nbsp;&nbsp;&nbsp;1.3.2</li>
<li>mp3diags:&nbsp;&nbsp;&nbsp;1.5.02</li>
<li>mps-youtube:&nbsp;&nbsp;&nbsp;0.2.8</li>
<li>ms-sys:&nbsp;&nbsp;&nbsp;2.6.0</li>
<li>msgpack-c:&nbsp;&nbsp;&nbsp;4.0.0</li>
<li>msgpack-python:&nbsp;&nbsp;&nbsp;1.0.3</li>
<li>msmtp:&nbsp;&nbsp;&nbsp;1.8.20</li>
<li>mtpfs:&nbsp;&nbsp;&nbsp;1.1</li>
<li>mu:&nbsp;&nbsp;&nbsp;1.6.10</li>
<li>multibootusb:&nbsp;&nbsp;&nbsp;9.2.0</li>
<li>mutagen:&nbsp;&nbsp;&nbsp;1.45.1</li>
<li>mypaint:&nbsp;&nbsp;&nbsp;2.0.1</li>
<li>mypaint-brushes2:&nbsp;&nbsp;&nbsp;2.0.2</li>
<li>mysqltuner:&nbsp;&nbsp;&nbsp;1.8.3</li>
<li>mystiq:&nbsp;&nbsp;&nbsp;20.03.23</li>
<li>nasty:&nbsp;&nbsp;&nbsp;0.6</li>
<li>nbtscan:&nbsp;&nbsp;&nbsp;1.7.2</li>
<li>ncrack:&nbsp;&nbsp;&nbsp;0.7</li>
<li>ndisc6:&nbsp;&nbsp;&nbsp;1.0.5</li>
<li>ndpi:&nbsp;&nbsp;&nbsp;4.2</li>
<li>neochat:&nbsp;&nbsp;&nbsp;1.2.0</li>
<li>neomutt:&nbsp;&nbsp;&nbsp;20211029</li>
<li>neomutt-vim:&nbsp;&nbsp;&nbsp;20200619</li>
<li>neovim:&nbsp;&nbsp;&nbsp;0.6.1</li>
<li>neovim-qt:&nbsp;&nbsp;&nbsp;0.2.16.1</li>
<li>neovim-remote:&nbsp;&nbsp;&nbsp;2.4.0</li>
<li>netbeans-bin:&nbsp;&nbsp;&nbsp;13</li>
<li>netcalc:&nbsp;&nbsp;&nbsp;2.1.6</li>
<li>netcat-openbsd:&nbsp;&nbsp;&nbsp;1.217</li>
<li>netdata:&nbsp;&nbsp;&nbsp;1.33.1</li>
<li>nethogs:&nbsp;&nbsp;&nbsp;0.8.6</li>
<li>netperf:&nbsp;&nbsp;&nbsp;2.7.0</li>
<li>netsniff-ng:&nbsp;&nbsp;&nbsp;0.6.8</li>
<li>netvisix:&nbsp;&nbsp;&nbsp;1.4.0</li>
<li>nghttp2-app:&nbsp;&nbsp;&nbsp;1.47.0</li>
<li>nginx:&nbsp;&nbsp;&nbsp;1.21.6</li>
<li>ngrep:&nbsp;&nbsp;&nbsp;1_47</li>
<li>nicstat:&nbsp;&nbsp;&nbsp;1.95</li>
<li>nikto:&nbsp;&nbsp;&nbsp;f6d99d0_git</li>
<li>nload:&nbsp;&nbsp;&nbsp;0.7.4</li>
<li>nnn:&nbsp;&nbsp;&nbsp;4.4</li>
<li>node-browserify:&nbsp;&nbsp;&nbsp;17.0.0</li>
<li>node-clean-css:&nbsp;&nbsp;&nbsp;5.2.4</li>
<li>node-clean-css-cli:&nbsp;&nbsp;&nbsp;5.5.2</li>
<li>node-cross-spawn:&nbsp;&nbsp;&nbsp;7.0.3</li>
<li>node-csscomb:&nbsp;&nbsp;&nbsp;4.3.0</li>
<li>node-doctoc:&nbsp;&nbsp;&nbsp;2.1.0</li>
<li>node-fs-extra:&nbsp;&nbsp;&nbsp;10.0.1</li>
<li>node-glob:&nbsp;&nbsp;&nbsp;7.2.0</li>
<li>node-gyp:&nbsp;&nbsp;&nbsp;9.0.0</li>
<li>node-less:&nbsp;&nbsp;&nbsp;4.1.2</li>
<li>node-libcli:&nbsp;&nbsp;&nbsp;5.3.0</li>
<li>node-mkdirp:&nbsp;&nbsp;&nbsp;1.0.4</li>
<li>node-nan:&nbsp;&nbsp;&nbsp;2.15.0</li>
<li>node-nativefier:&nbsp;&nbsp;&nbsp;46.2.0</li>
<li>node-purifycss:&nbsp;&nbsp;&nbsp;1.2.6</li>
<li>node-sass:&nbsp;&nbsp;&nbsp;7.0.1</li>
<li>node-semver:&nbsp;&nbsp;&nbsp;7.3.5</li>
<li>node-stylus:&nbsp;&nbsp;&nbsp;0.57.0</li>
<li>node-uglifycss:&nbsp;&nbsp;&nbsp;0.0.29</li>
<li>node-uglifyjs:&nbsp;&nbsp;&nbsp;3.15.3</li>
<li>node-unminify:&nbsp;&nbsp;&nbsp;75d64f6</li>
<li>nomacs:&nbsp;&nbsp;&nbsp;3.17.2206</li>
<li>notmuch:&nbsp;&nbsp;&nbsp;0.35</li>
<li>npm-check:&nbsp;&nbsp;&nbsp;5.9.2</li>
<li>npm-check-updates:&nbsp;&nbsp;&nbsp;12.5.4</li>
<li>ntopng:&nbsp;&nbsp;&nbsp;5.2.1</li>
<li>numactl:&nbsp;&nbsp;&nbsp;2.0.14</li>
<li>numpy:&nbsp;&nbsp;&nbsp;1.22.3</li>
<li>nuttcp:&nbsp;&nbsp;&nbsp;8.2.2</li>
<li>nvchecker:&nbsp;&nbsp;&nbsp;2.7</li>
<li>nyx:&nbsp;&nbsp;&nbsp;2.1.0</li>
<li>oauth2client:&nbsp;&nbsp;&nbsp;4.1.3</li>
<li>obs-studio:&nbsp;&nbsp;&nbsp;27.2.4</li>
<li>offlineimap:&nbsp;&nbsp;&nbsp;7.3.4</li>
<li>ok_sh:&nbsp;&nbsp;&nbsp;0.7.0</li>
<li>omping:&nbsp;&nbsp;&nbsp;0.0.4</li>
<li>onefetch:&nbsp;&nbsp;&nbsp;2.12.0</li>
<li>openblas:&nbsp;&nbsp;&nbsp;0.3.20</li>
<li>openmpi:&nbsp;&nbsp;&nbsp;4.1.2</li>
<li>opensc:&nbsp;&nbsp;&nbsp;0.22.0</li>
<li>openshot:&nbsp;&nbsp;&nbsp;2.6.1</li>
<li>ophcrack:&nbsp;&nbsp;&nbsp;3.8.0</li>
<li>optipng:&nbsp;&nbsp;&nbsp;0.7.7</li>
<li>osinfo-db:&nbsp;&nbsp;&nbsp;20220214</li>
<li>osinfo-db-tools:&nbsp;&nbsp;&nbsp;1.10.0</li>
<li>ostinato:&nbsp;&nbsp;&nbsp;1.1</li>
<li>owamp:&nbsp;&nbsp;&nbsp;4.4.3</li>
<li>oxipng:&nbsp;&nbsp;&nbsp;5.0.1</li>
<li>p0f:&nbsp;&nbsp;&nbsp;3.09b</li>
<li>p7zip:&nbsp;&nbsp;&nbsp;17.04</li>
<li>packeth:&nbsp;&nbsp;&nbsp;2.1</li>
<li>pandoc-bin:&nbsp;&nbsp;&nbsp;2.17.1.1</li>
<li>paperkey:&nbsp;&nbsp;&nbsp;1.6</li>
<li>par2cmdline:&nbsp;&nbsp;&nbsp;0.8.1</li>
<li>paramiko:&nbsp;&nbsp;&nbsp;2.10.3</li>
<li>pbzip2:&nbsp;&nbsp;&nbsp;1.1.13</li>
<li>pcsc-lite:&nbsp;&nbsp;&nbsp;1.9.5</li>
<li>pcsc-perl:&nbsp;&nbsp;&nbsp;1.4.14</li>
<li>pcsc-tools:&nbsp;&nbsp;&nbsp;1.6.0</li>
<li>pdfarranger:&nbsp;&nbsp;&nbsp;1.8.2</li>
<li>pdfgrep:&nbsp;&nbsp;&nbsp;2.1.2</li>
<li>pdfsam-bin:&nbsp;&nbsp;&nbsp;4.2.12</li>
<li>pdftricks:&nbsp;&nbsp;&nbsp;0.4.1</li>
<li>pdsh:&nbsp;&nbsp;&nbsp;2.34</li>
<li>percona-toolkit:&nbsp;&nbsp;&nbsp;3.3.1</li>
<li>perl-digest-md4:&nbsp;&nbsp;&nbsp;1.9</li>
<li>perl-io-tty:&nbsp;&nbsp;&nbsp;1.16</li>
<li>perl-json:&nbsp;&nbsp;&nbsp;4.05</li>
<li>phan:&nbsp;&nbsp;&nbsp;5.3.2</li>
<li>phive:&nbsp;&nbsp;&nbsp;0.15.1</li>
<li>phoneinfoga-bin:&nbsp;&nbsp;&nbsp;2.3.8</li>
<li>photoqt:&nbsp;&nbsp;&nbsp;2.5</li>
<li>php-antimalware-scanner:&nbsp;&nbsp;&nbsp;0.10.2</li>
<li>php-apcu:&nbsp;&nbsp;&nbsp;5.1.21</li>
<li>php-ast:&nbsp;&nbsp;&nbsp;1.0.16</li>
<li>php-composer:&nbsp;&nbsp;&nbsp;2.3.1</li>
<li>php-igbinary:&nbsp;&nbsp;&nbsp;3.2.7</li>
<li>php-imagick:&nbsp;&nbsp;&nbsp;3.7.0</li>
<li>php-memcache:&nbsp;&nbsp;&nbsp;8.0</li>
<li>php-memcached:&nbsp;&nbsp;&nbsp;3.2.0</li>
<li>php-msgpack:&nbsp;&nbsp;&nbsp;2.1.2</li>
<li>php-oauth:&nbsp;&nbsp;&nbsp;2.0.7</li>
<li>php-redis:&nbsp;&nbsp;&nbsp;5.3.7</li>
<li>php-stat:&nbsp;&nbsp;&nbsp;eff23e7</li>
<li>php-xdebug:&nbsp;&nbsp;&nbsp;3.1.3</li>
<li>phpdocumentor:&nbsp;&nbsp;&nbsp;3.3.1</li>
<li>phpspy:&nbsp;&nbsp;&nbsp;5f2368f</li>
<li>pipewire-jack:&nbsp;&nbsp;&nbsp;0.3.49</li>
<li>pixiewps:&nbsp;&nbsp;&nbsp;1.4.2</li>
<li>pkgdiff:&nbsp;&nbsp;&nbsp;1.7.2</li>
<li>pmacct:&nbsp;&nbsp;&nbsp;1.7.7</li>
<li>pmount:&nbsp;&nbsp;&nbsp;0.9.23</li>
<li>pngcrush:&nbsp;&nbsp;&nbsp;1.8.13</li>
<li>pngout-bin:&nbsp;&nbsp;&nbsp;20200115</li>
<li>podofo:&nbsp;&nbsp;&nbsp;0.9.7</li>
<li>poedit:&nbsp;&nbsp;&nbsp;3.0.1</li>
<li>postcss:&nbsp;&nbsp;&nbsp;8.4.12</li>
<li>postcss-autoprefixer:&nbsp;&nbsp;&nbsp;10.4.2</li>
<li>postcss-cli:&nbsp;&nbsp;&nbsp;8.0.0</li>
<li>postgresql:&nbsp;&nbsp;&nbsp;14.2</li>
<li>postman-bin:&nbsp;&nbsp;&nbsp;9.15.2</li>
<li>potrace:&nbsp;&nbsp;&nbsp;1.16</li>
<li>privoxy:&nbsp;&nbsp;&nbsp;3.0.33</li>
<li>profanity:&nbsp;&nbsp;&nbsp;0.11.1</li>
<li>prompt-toolkit:&nbsp;&nbsp;&nbsp;3.0.28</li>
<li>protobuf:&nbsp;&nbsp;&nbsp;3.19.4</li>
<li>protobuf-c:&nbsp;&nbsp;&nbsp;1.4.0</li>
<li>psensor:&nbsp;&nbsp;&nbsp;1.2.1</li>
<li>pstoedit:&nbsp;&nbsp;&nbsp;3.78</li>
<li>psutil:&nbsp;&nbsp;&nbsp;5.9.0</li>
<li>psycopg2:&nbsp;&nbsp;&nbsp;2.9.3</li>
<li>pugixml:&nbsp;&nbsp;&nbsp;1.12.1</li>
<li>purgecss:&nbsp;&nbsp;&nbsp;4.1.3</li>
<li>purgecss-with-wordpress:&nbsp;&nbsp;&nbsp;4.1.0</li>
<li>putty:&nbsp;&nbsp;&nbsp;0.76</li>
<li>pv:&nbsp;&nbsp;&nbsp;1.6.20</li>
<li>pwgen:&nbsp;&nbsp;&nbsp;2.08</li>
<li>pyasn1:&nbsp;&nbsp;&nbsp;0.4.8</li>
<li>pyasn1-modules:&nbsp;&nbsp;&nbsp;0.2.8</li>
<li>pybind11:&nbsp;&nbsp;&nbsp;2.9.1</li>
<li>pycrypto:&nbsp;&nbsp;&nbsp;2.6.1</li>
<li>pycryptodomex:&nbsp;&nbsp;&nbsp;3.14.1</li>
<li>pyinotify:&nbsp;&nbsp;&nbsp;0.9.6</li>
<li>pylibacl:&nbsp;&nbsp;&nbsp;0.6.0</li>
<li>pynacl:&nbsp;&nbsp;&nbsp;1.5.0</li>
<li>pynvim:&nbsp;&nbsp;&nbsp;0.4.3</li>
<li>pypubsub:&nbsp;&nbsp;&nbsp;4.0.3</li>
<li>pyquery:&nbsp;&nbsp;&nbsp;1.4.3</li>
<li>pyrit:&nbsp;&nbsp;&nbsp;0.5.0</li>
<li>pysocks:&nbsp;&nbsp;&nbsp;1.7.1</li>
<li>pyte:&nbsp;&nbsp;&nbsp;0.8.0</li>
<li>python-attrs:&nbsp;&nbsp;&nbsp;21.4.0</li>
<li>python-babel:&nbsp;&nbsp;&nbsp;2.9.1</li>
<li>python-bcrypt:&nbsp;&nbsp;&nbsp;3.2.0</li>
<li>python-botocore:&nbsp;&nbsp;&nbsp;1.24.29</li>
<li>python-cached-property:&nbsp;&nbsp;&nbsp;1.5.2</li>
<li>python-cheetah3:&nbsp;&nbsp;&nbsp;3.2.6.post1</li>
<li>python-cssselect:&nbsp;&nbsp;&nbsp;1.1.0</li>
<li>python-dateutil:&nbsp;&nbsp;&nbsp;2.8.2</li>
<li>python-distutils-extra:&nbsp;&nbsp;&nbsp;2.39</li>
<li>python-docopt:&nbsp;&nbsp;&nbsp;0.6.2</li>
<li>python-evdev:&nbsp;&nbsp;&nbsp;1.5.0</li>
<li>python-fuse:&nbsp;&nbsp;&nbsp;1.0.4</li>
<li>python-h11:&nbsp;&nbsp;&nbsp;0.13.0</li>
<li>python-h2:&nbsp;&nbsp;&nbsp;4.1.0</li>
<li>python-hpack:&nbsp;&nbsp;&nbsp;4.0.0</li>
<li>python-hstspreload:&nbsp;&nbsp;&nbsp;2021.12.1</li>
<li>python-httpx:&nbsp;&nbsp;&nbsp;0.22.0</li>
<li>python-hyperframe:&nbsp;&nbsp;&nbsp;6.0.1</li>
<li>python-importlib-metadata:&nbsp;&nbsp;&nbsp;4.11.3</li>
<li>python-jmespath:&nbsp;&nbsp;&nbsp;1.0.0</li>
<li>python-jsonschema:&nbsp;&nbsp;&nbsp;4.4.0</li>
<li>python-keyring:&nbsp;&nbsp;&nbsp;23.5.0</li>
<li>python-logzero:&nbsp;&nbsp;&nbsp;1.7.0</li>
<li>python-lyricwikia:&nbsp;&nbsp;&nbsp;0.1.11</li>
<li>python-magic:&nbsp;&nbsp;&nbsp;0.4.25</li>
<li>python-oauthlib:&nbsp;&nbsp;&nbsp;3.2.0</li>
<li>python-pafy:&nbsp;&nbsp;&nbsp;0.5.5</li>
<li>python-pathlib:&nbsp;&nbsp;&nbsp;1.0.1</li>
<li>python-pathlib2:&nbsp;&nbsp;&nbsp;2.3.7.post1</li>
<li>python-pikepdf:&nbsp;&nbsp;&nbsp;5.1.1</li>
<li>python-polib:&nbsp;&nbsp;&nbsp;1.1.1</li>
<li>python-pycodestyle:&nbsp;&nbsp;&nbsp;2.8.0</li>
<li>python-pyrsistent:&nbsp;&nbsp;&nbsp;0.18.1</li>
<li>python-pyzmq:&nbsp;&nbsp;&nbsp;22.3.0</li>
<li>python-rapidfuzz:&nbsp;&nbsp;&nbsp;2.0.7</li>
<li>python-redis:&nbsp;&nbsp;&nbsp;4.2.0</li>
<li>python-regex:&nbsp;&nbsp;&nbsp;2022.3.15</li>
<li>python-requests-oauthlib:&nbsp;&nbsp;&nbsp;1.3.1</li>
<li>python-requests-toolbelt:&nbsp;&nbsp;&nbsp;0.9.1</li>
<li>python-rfc3986:&nbsp;&nbsp;&nbsp;2.0.0</li>
<li>python-rfc6555:&nbsp;&nbsp;&nbsp;0.1.0</li>
<li>python-s3transfer:&nbsp;&nbsp;&nbsp;0.5.2</li>
<li>python-selectors2:&nbsp;&nbsp;&nbsp;2.0.2</li>
<li>python-semantic_version:&nbsp;&nbsp;&nbsp;2.9.0</li>
<li>python-setuptools-rust:&nbsp;&nbsp;&nbsp;1.2.0</li>
<li>python-slip:&nbsp;&nbsp;&nbsp;0.6.5</li>
<li>python-sniffio:&nbsp;&nbsp;&nbsp;1.2.0</li>
<li>python-spotipy:&nbsp;&nbsp;&nbsp;2.19.0</li>
<li>python-structlog:&nbsp;&nbsp;&nbsp;21.5.0</li>
<li>python-texttable:&nbsp;&nbsp;&nbsp;1.6.4</li>
<li>python-titlecase:&nbsp;&nbsp;&nbsp;2.3</li>
<li>python-tld:&nbsp;&nbsp;&nbsp;0.12.6</li>
<li>python-toml:&nbsp;&nbsp;&nbsp;0.10.2</li>
<li>python-tornado:&nbsp;&nbsp;&nbsp;6.1</li>
<li>python-tqdm:&nbsp;&nbsp;&nbsp;4.63.1</li>
<li>python-typing-extensions:&nbsp;&nbsp;&nbsp;4.1.1</li>
<li>python-typing_extensions:&nbsp;&nbsp;&nbsp;4.0.1</li>
<li>python-ujson:&nbsp;&nbsp;&nbsp;5.1.0</li>
<li>python-unidecode:&nbsp;&nbsp;&nbsp;1.3.4</li>
<li>python-uritemplate:&nbsp;&nbsp;&nbsp;4.1.1</li>
<li>python-urwid:&nbsp;&nbsp;&nbsp;2.1.2</li>
<li>python-vimgolf:&nbsp;&nbsp;&nbsp;0.4.1</li>
<li>python-webencodings:&nbsp;&nbsp;&nbsp;0.5.1</li>
<li>python-websocket-client:&nbsp;&nbsp;&nbsp;1.3.2</li>
<li>python-websockets:&nbsp;&nbsp;&nbsp;10.2</li>
<li>python-wheel:&nbsp;&nbsp;&nbsp;0.37.1</li>
<li>python-xlib:&nbsp;&nbsp;&nbsp;0.21</li>
<li>python-zipp:&nbsp;&nbsp;&nbsp;3.7.0</li>
<li>python2-rfc6555:&nbsp;&nbsp;&nbsp;0.0.0</li>
<li>python2-selectors2:&nbsp;&nbsp;&nbsp;2.0.2</li>
<li>python2-ujson:&nbsp;&nbsp;&nbsp;2.0.3</li>
<li>pythondialog:&nbsp;&nbsp;&nbsp;3.5.3</li>
<li>pytube3:&nbsp;&nbsp;&nbsp;9.6.4</li>
<li>pytz:&nbsp;&nbsp;&nbsp;2022.1</li>
<li>pyudev:&nbsp;&nbsp;&nbsp;0.23.2</li>
<li>pywakeonlan:&nbsp;&nbsp;&nbsp;2.1.0</li>
<li>pyxattr:&nbsp;&nbsp;&nbsp;0.7.2</li>
<li>pyyaml:&nbsp;&nbsp;&nbsp;6.0</li>
<li>q4wine:&nbsp;&nbsp;&nbsp;1.3.13</li>
<li>qbittorrent:&nbsp;&nbsp;&nbsp;4.4.2</li>
<li>qdirstat:&nbsp;&nbsp;&nbsp;1.8</li>
<li>qemu:&nbsp;&nbsp;&nbsp;6.2.0</li>
<li>qjackctl:&nbsp;&nbsp;&nbsp;0.9.6</li>
<li>qnetstatview:&nbsp;&nbsp;&nbsp;1.5.6</li>
<li>qoauth:&nbsp;&nbsp;&nbsp;2.0.0</li>
<li>qt-heif-image-plugin:&nbsp;&nbsp;&nbsp;3ab3539</li>
<li>qt5ct:&nbsp;&nbsp;&nbsp;1.5</li>
<li>qtcurve:&nbsp;&nbsp;&nbsp;be78a85</li>
<li>qtpass:&nbsp;&nbsp;&nbsp;1.3.2</li>
<li>qtspell:&nbsp;&nbsp;&nbsp;1.0.1</li>
<li>qwt:&nbsp;&nbsp;&nbsp;6.1.6</li>
<li>qxmledit:&nbsp;&nbsp;&nbsp;0.9.16</li>
<li>ragel:&nbsp;&nbsp;&nbsp;6.10</li>
<li>ranger:&nbsp;&nbsp;&nbsp;1.9.3</li>
<li>rawtherapee:&nbsp;&nbsp;&nbsp;5.8</li>
<li>rchardet:&nbsp;&nbsp;&nbsp;1.8.0</li>
<li>rclone:&nbsp;&nbsp;&nbsp;1.58.0</li>
<li>reaver:&nbsp;&nbsp;&nbsp;1.6.6</li>
<li>redis:&nbsp;&nbsp;&nbsp;6.2.6</li>
<li>reportlab:&nbsp;&nbsp;&nbsp;3.6.9</li>
<li>reppy2:&nbsp;&nbsp;&nbsp;0.3.6</li>
<li>responsively-app:&nbsp;&nbsp;&nbsp;0.18.0</li>
<li>rest:&nbsp;&nbsp;&nbsp;0.8.1</li>
<li>rkhunter:&nbsp;&nbsp;&nbsp;1.4.6</li>
<li>rlog:&nbsp;&nbsp;&nbsp;1.4</li>
<li>rrdtool:&nbsp;&nbsp;&nbsp;1.7.2</li>
<li>rsa:&nbsp;&nbsp;&nbsp;4.8</li>
<li>rtmpdump:&nbsp;&nbsp;&nbsp;2.4_f1b83c1</li>
<li>rtorrent:&nbsp;&nbsp;&nbsp;0.9.8</li>
<li>ruamel-yaml:&nbsp;&nbsp;&nbsp;0.17.21</li>
<li>runc:&nbsp;&nbsp;&nbsp;1.1.1</li>
<li>ruyaml:&nbsp;&nbsp;&nbsp;0.91.0</li>
<li>s3fs-fuse:&nbsp;&nbsp;&nbsp;1.91</li>
<li>safecopy:&nbsp;&nbsp;&nbsp;1.7</li>
<li>samhain:&nbsp;&nbsp;&nbsp;4.4.7</li>
<li>sarg:&nbsp;&nbsp;&nbsp;2.4.0</li>
<li>sbbdep:&nbsp;&nbsp;&nbsp;0.3.2</li>
<li>scanmem:&nbsp;&nbsp;&nbsp;0.17</li>
<li>scanssh:&nbsp;&nbsp;&nbsp;2.1.2</li>
<li>scapy:&nbsp;&nbsp;&nbsp;2.4.5</li>
<li>scour:&nbsp;&nbsp;&nbsp;0.38.2</li>
<li>screamingfrogseospider-bin:&nbsp;&nbsp;&nbsp;16.6</li>
<li>scribus:&nbsp;&nbsp;&nbsp;1.5.8</li>
<li>sdl_sound:&nbsp;&nbsp;&nbsp;1.0.3</li>
<li>seahorse:&nbsp;&nbsp;&nbsp;40.0</li>
<li>secretstorage:&nbsp;&nbsp;&nbsp;3.3.1</li>
<li>securefs:&nbsp;&nbsp;&nbsp;0.12.0</li>
<li>sencrypt:&nbsp;&nbsp;&nbsp;4</li>
<li>setconf:&nbsp;&nbsp;&nbsp;0.7.7</li>
<li>shellcheck-bin:&nbsp;&nbsp;&nbsp;0.8.0</li>
<li>shorewall:&nbsp;&nbsp;&nbsp;5.2.8</li>
<li>shorewall-core:&nbsp;&nbsp;&nbsp;5.2.8</li>
<li>shorewall6:&nbsp;&nbsp;&nbsp;5.2.8</li>
<li>siege:&nbsp;&nbsp;&nbsp;4.1.2</li>
<li>signal-desktop-bin:&nbsp;&nbsp;&nbsp;5.36.0</li>
<li>signon-kwallet-extension:&nbsp;&nbsp;&nbsp;21.12.3</li>
<li>signon-plugin-oauth2:&nbsp;&nbsp;&nbsp;0.24_d759439</li>
<li>signon-ui:&nbsp;&nbsp;&nbsp;0.17_4368bb77</li>
<li>signond:&nbsp;&nbsp;&nbsp;8.60</li>
<li>simplejson:&nbsp;&nbsp;&nbsp;3.17.6</li>
<li>simplenote-bin:&nbsp;&nbsp;&nbsp;2.21.0</li>
<li>sipcalc:&nbsp;&nbsp;&nbsp;1.1.6</li>
<li>sirikali:&nbsp;&nbsp;&nbsp;1.4.8</li>
<li>sitemap-generator:&nbsp;&nbsp;&nbsp;8.5.1</li>
<li>sitemap-generator-cli:&nbsp;&nbsp;&nbsp;7.5.0</li>
<li>sitespeedio:&nbsp;&nbsp;&nbsp;23.6.1</li>
<li>skypeforlinux-bin:&nbsp;&nbsp;&nbsp;8.83.76.100</li>
<li>slack-bin:&nbsp;&nbsp;&nbsp;4.24.0</li>
<li>sleuthkit:&nbsp;&nbsp;&nbsp;4.11.1</li>
<li>slpkg:&nbsp;&nbsp;&nbsp;3.9.4</li>
<li>slurm:&nbsp;&nbsp;&nbsp;0.4.3</li>
<li>smb4k:&nbsp;&nbsp;&nbsp;3.1.1</li>
<li>smbnetfs:&nbsp;&nbsp;&nbsp;0.6.3</li>
<li>smem:&nbsp;&nbsp;&nbsp;1.4</li>
<li>smmap2:&nbsp;&nbsp;&nbsp;3.0.1</li>
<li>smplayer:&nbsp;&nbsp;&nbsp;22.2.0</li>
<li>smplayer-skins:&nbsp;&nbsp;&nbsp;20130605</li>
<li>smplayer-themes:&nbsp;&nbsp;&nbsp;20140607</li>
<li>smtube:&nbsp;&nbsp;&nbsp;21.10.0</li>
<li>snappy:&nbsp;&nbsp;&nbsp;1.1.9</li>
<li>sniffit:&nbsp;&nbsp;&nbsp;0.5</li>
<li>snowballstemmer:&nbsp;&nbsp;&nbsp;2.2.0</li>
<li>solaar:&nbsp;&nbsp;&nbsp;1.1.2</li>
<li>soundkonverter:&nbsp;&nbsp;&nbsp;3.0.1</li>
<li>soundtouch:&nbsp;&nbsp;&nbsp;2.3.1</li>
<li>soupsieve:&nbsp;&nbsp;&nbsp;2.3.1</li>
<li>sparse:&nbsp;&nbsp;&nbsp;0.6.4</li>
<li>speedtest-cli:&nbsp;&nbsp;&nbsp;2.1.2</li>
<li>sphinx:&nbsp;&nbsp;&nbsp;4.5.0</li>
<li>spice:&nbsp;&nbsp;&nbsp;0.15.0</li>
<li>spice-gtk:&nbsp;&nbsp;&nbsp;0.40</li>
<li>spice-protocol:&nbsp;&nbsp;&nbsp;0.14.4</li>
<li>splitjob:&nbsp;&nbsp;&nbsp;3.0</li>
<li>spotify-bin:&nbsp;&nbsp;&nbsp;1.1.42</li>
<li>spotify-downloader:&nbsp;&nbsp;&nbsp;3.9.3</li>
<li>sqlcheck:&nbsp;&nbsp;&nbsp;1.3</li>
<li>sqlitebrowser:&nbsp;&nbsp;&nbsp;3.12.2</li>
<li>sqlmap:&nbsp;&nbsp;&nbsp;1.6.2</li>
<li>squid:&nbsp;&nbsp;&nbsp;4.17</li>
<li>srm:&nbsp;&nbsp;&nbsp;1.2.15</li>
<li>ssdeep:&nbsp;&nbsp;&nbsp;2.14.1</li>
<li>ssh-audit:&nbsp;&nbsp;&nbsp;2.5.0</li>
<li>ssh-tools:&nbsp;&nbsp;&nbsp;1.7</li>
<li>sshguard:&nbsp;&nbsp;&nbsp;2.4.2</li>
<li>sshpass:&nbsp;&nbsp;&nbsp;1.09</li>
<li>sshrc:&nbsp;&nbsp;&nbsp;0.6.2</li>
<li>sshtunnel:&nbsp;&nbsp;&nbsp;0.4.0</li>
<li>sslh:&nbsp;&nbsp;&nbsp;1.22c</li>
<li>sslscan:&nbsp;&nbsp;&nbsp;2.0.12</li>
<li>sslsplit:&nbsp;&nbsp;&nbsp;0.5.5</li>
<li>stem:&nbsp;&nbsp;&nbsp;1.8.0</li>
<li>stylelint:&nbsp;&nbsp;&nbsp;14.6.1</li>
<li>stylelint-config-recommended:&nbsp;&nbsp;&nbsp;7.0.0</li>
<li>stylelint-config-standard:&nbsp;&nbsp;&nbsp;25.0.0</li>
<li>subfinder:&nbsp;&nbsp;&nbsp;2.5.0</li>
<li>subtitlecomposer:&nbsp;&nbsp;&nbsp;0.7.1</li>
<li>subtitleeditor:&nbsp;&nbsp;&nbsp;4c215f4</li>
<li>suricata:&nbsp;&nbsp;&nbsp;6.0.4</li>
<li>svgo:&nbsp;&nbsp;&nbsp;2.8.0</li>
<li>tbb:&nbsp;&nbsp;&nbsp;2021.5.0</li>
<li>tc-play:&nbsp;&nbsp;&nbsp;3.3</li>
<li>tcpick:&nbsp;&nbsp;&nbsp;0.2.1</li>
<li>tcptrack:&nbsp;&nbsp;&nbsp;1.4.3</li>
<li>teamviewer-bin:&nbsp;&nbsp;&nbsp;15.28.6</li>
<li>telegram-bin:&nbsp;&nbsp;&nbsp;3.6.1</li>
<li>tellico:&nbsp;&nbsp;&nbsp;3.4.4</li>
<li>termbox:&nbsp;&nbsp;&nbsp;1.1.2</li>
<li>tesseract:&nbsp;&nbsp;&nbsp;5.0.1</li>
<li>testdisk:&nbsp;&nbsp;&nbsp;7.1</li>
<li>testssl_sh:&nbsp;&nbsp;&nbsp;3.0.7</li>
<li>thc-ipv6:&nbsp;&nbsp;&nbsp;3.8</li>
<li>thefuck:&nbsp;&nbsp;&nbsp;3.32</li>
<li>tig:&nbsp;&nbsp;&nbsp;2.5.5</li>
<li>tilda:&nbsp;&nbsp;&nbsp;1.5.0</li>
<li>timidity:&nbsp;&nbsp;&nbsp;2.15.0</li>
<li>tini:&nbsp;&nbsp;&nbsp;0.19.0</li>
<li>tinycss2:&nbsp;&nbsp;&nbsp;1.1.1</li>
<li>tinyxml:&nbsp;&nbsp;&nbsp;2.6.2</li>
<li>tinyxml2:&nbsp;&nbsp;&nbsp;9.0.0</li>
<li>tokyocabinet:&nbsp;&nbsp;&nbsp;1.4.48</li>
<li>tomb:&nbsp;&nbsp;&nbsp;2.9</li>
<li>tor:&nbsp;&nbsp;&nbsp;0.4.6.10</li>
<li>torrent-file-editor:&nbsp;&nbsp;&nbsp;0.3.17</li>
<li>torsocks:&nbsp;&nbsp;&nbsp;2.3.0</li>
<li>trash-cli:&nbsp;&nbsp;&nbsp;0.21.10.24</li>
<li>tree-sitter:&nbsp;&nbsp;&nbsp;0.20.6</li>
<li>trimage:&nbsp;&nbsp;&nbsp;1.0.6</li>
<li>trojita:&nbsp;&nbsp;&nbsp;0.7</li>
<li>tunctl:&nbsp;&nbsp;&nbsp;1.5</li>
<li>tweepy:&nbsp;&nbsp;&nbsp;4.8.0</li>
<li>twitter:&nbsp;&nbsp;&nbsp;1.19.3</li>
<li>twolame:&nbsp;&nbsp;&nbsp;0.4.0</li>
<li>txt2man:&nbsp;&nbsp;&nbsp;1.7.1</li>
<li>typescript:&nbsp;&nbsp;&nbsp;4.6.3</li>
<li>udiskie:&nbsp;&nbsp;&nbsp;2.4.1</li>
<li>ufw:&nbsp;&nbsp;&nbsp;0.36.1</li>
<li>uget:&nbsp;&nbsp;&nbsp;2.2.3</li>
<li>unetbootin:&nbsp;&nbsp;&nbsp;702</li>
<li>unhide:&nbsp;&nbsp;&nbsp;20130526</li>
<li>uni2ascii:&nbsp;&nbsp;&nbsp;4.18</li>
<li>unibilium:&nbsp;&nbsp;&nbsp;92d929f</li>
<li>unicode-character-database:&nbsp;&nbsp;&nbsp;14.0.0</li>
<li>unicode-emoji:&nbsp;&nbsp;&nbsp;14.0</li>
<li>unicode-slugify:&nbsp;&nbsp;&nbsp;0.1.5</li>
<li>unittest-cpp:&nbsp;&nbsp;&nbsp;2.0.0</li>
<li>universal-ctags:&nbsp;&nbsp;&nbsp;p5.9.20220327.0</li>
<li>unix-privesc-check:&nbsp;&nbsp;&nbsp;2.1_git4239100</li>
<li>unoconv:&nbsp;&nbsp;&nbsp;0.9.0</li>
<li>unrar:&nbsp;&nbsp;&nbsp;6.1.6</li>
<li>unrtf:&nbsp;&nbsp;&nbsp;0.21.10</li>
<li>urlgrabber:&nbsp;&nbsp;&nbsp;4.1.0</li>
<li>urlscan:&nbsp;&nbsp;&nbsp;0.9.9</li>
<li>urlwatch:&nbsp;&nbsp;&nbsp;2.25</li>
<li>usbredir:&nbsp;&nbsp;&nbsp;0.8.0</li>
<li>uuid:&nbsp;&nbsp;&nbsp;1.6.2</li>
<li>valentina-studio-bin:&nbsp;&nbsp;&nbsp;12.1</li>
<li>valgrind:&nbsp;&nbsp;&nbsp;3.18.1</li>
<li>varnish:&nbsp;&nbsp;&nbsp;7.1.0</li>
<li>vde2:&nbsp;&nbsp;&nbsp;2.3.2</li>
<li>vdt:&nbsp;&nbsp;&nbsp;5.4.68</li>
<li>vegeta-bin:&nbsp;&nbsp;&nbsp;12.8.4</li>
<li>veracrypt:&nbsp;&nbsp;&nbsp;1.25.9</li>
<li>vifm:&nbsp;&nbsp;&nbsp;0.12</li>
<li>vimb:&nbsp;&nbsp;&nbsp;3.6.0</li>
<li>vimtips:&nbsp;&nbsp;&nbsp;0.2.7</li>
<li>virglrenderer:&nbsp;&nbsp;&nbsp;0.9.1</li>
<li>virt-manager:&nbsp;&nbsp;&nbsp;3.2.0</li>
<li>virt-viewer:&nbsp;&nbsp;&nbsp;11.0</li>
<li>vkd3d:&nbsp;&nbsp;&nbsp;1.3</li>
<li>vnstat:&nbsp;&nbsp;&nbsp;2.9</li>
<li>vscodium-bin:&nbsp;&nbsp;&nbsp;1.65.2</li>
<li>vuescan-bin:&nbsp;&nbsp;&nbsp;9.7.82</li>
<li>vulscan:&nbsp;&nbsp;&nbsp;2.1</li>
<li>w3m:&nbsp;&nbsp;&nbsp;0.5.3</li>
<li>wapiti3:&nbsp;&nbsp;&nbsp;3.1.1</li>
<li>wcwidth:&nbsp;&nbsp;&nbsp;0.2.5</li>
<li>wdiff:&nbsp;&nbsp;&nbsp;1.2.2</li>
<li>webcoach:&nbsp;&nbsp;&nbsp;7.0.0</li>
<li>webkitgtk:&nbsp;&nbsp;&nbsp;2.36.0</li>
<li>websocketpp:&nbsp;&nbsp;&nbsp;0.8.2</li>
<li>weechat:&nbsp;&nbsp;&nbsp;3.5</li>
<li>whatweb:&nbsp;&nbsp;&nbsp;0.5.5</li>
<li>whowatch:&nbsp;&nbsp;&nbsp;1.8.6</li>
<li>wifite:&nbsp;&nbsp;&nbsp;2.0.89</li>
<li>winetricks:&nbsp;&nbsp;&nbsp;20220328</li>
<li>wipe:&nbsp;&nbsp;&nbsp;2.3.1</li>
<li>wireshark:&nbsp;&nbsp;&nbsp;3.6.3</li>
<li>wol:&nbsp;&nbsp;&nbsp;0.7.1</li>
<li>wol_qt:&nbsp;&nbsp;&nbsp;2.4</li>
<li>wp-cli:&nbsp;&nbsp;&nbsp;2.6.0</li>
<li>wpebackend-fdo:&nbsp;&nbsp;&nbsp;1.12.0</li>
<li>wpscan:&nbsp;&nbsp;&nbsp;3.8.21</li>
<li>wput:&nbsp;&nbsp;&nbsp;0.6.2</li>
<li>wxgtk:&nbsp;&nbsp;&nbsp;3.0.5.1</li>
<li>x11vnc:&nbsp;&nbsp;&nbsp;0.9.16</li>
<li>x264:&nbsp;&nbsp;&nbsp;bfc87b7</li>
<li>x265:&nbsp;&nbsp;&nbsp;3.4</li>
<li>xbill:&nbsp;&nbsp;&nbsp;2.1</li>
<li>xclip:&nbsp;&nbsp;&nbsp;0.13</li>
<li>xdg-dbus-proxy:&nbsp;&nbsp;&nbsp;0.1.3</li>
<li>xh:&nbsp;&nbsp;&nbsp;0.15.0</li>
<li>xmltoman:&nbsp;&nbsp;&nbsp;0.6</li>
<li>xping:&nbsp;&nbsp;&nbsp;1.4.2</li>
<li>xsel:&nbsp;&nbsp;&nbsp;git_062e6d3</li>
<li>yajl:&nbsp;&nbsp;&nbsp;2.1.0</li>
<li>yapet:&nbsp;&nbsp;&nbsp;2.6</li>
<li>yara:&nbsp;&nbsp;&nbsp;4.2.0</li>
<li>yara-python:&nbsp;&nbsp;&nbsp;4.2.0</li>
<li>yarn:&nbsp;&nbsp;&nbsp;1.22.18</li>
<li>yaswfp:&nbsp;&nbsp;&nbsp;0.9.3</li>
<li>youtube-dl:&nbsp;&nbsp;&nbsp;2021.12.17</li>
<li>yt-dlp:&nbsp;&nbsp;&nbsp;2022.3.8.2</li>
<li>zenity:&nbsp;&nbsp;&nbsp;3.41.0</li>
<li>zeromq:&nbsp;&nbsp;&nbsp;4.3.4</li>
<li>zmap:&nbsp;&nbsp;&nbsp;2.1.1</li>
<li>zulucrypt:&nbsp;&nbsp;&nbsp;6.0.0</li>
<li>zuluplay:&nbsp;&nbsp;&nbsp;1.1</li>
</ul></div>
<hr>

<p><b>Repository contains 64bit packages for Slackware Current</b><br>
Each directory contain the binary packages, ready for installation using
'installpkg' or 'upgradepkg'. You'll find *.txz (the package itself),
*.txt (the package description) and *.md5 (containing the md5 checksum of the
package) files in each directory.</p>
<p><b>-extra</b> repository contains packages that need external dependencies, not present in my repository, like kde5 for example.</p>
<p>
SLACKBUILD and other files needed for compiling packages can be found on <a href="https://github.com/conraid/SlackBuilds" target="_blank" rel="external noopener" title="Vai al repositoty su GitHub">GitHub</a>
</p>
<p>If you have any questions or requests,you can contact me at conrad (at) linux (dot) it</p>

<p>Mirror:<br>
- <a href="/repository">Main site</a> - This repository.
<br>
- <a href="https://sourceforge.net/projects/slackers/files/" target="_blank" title="Vai sul mirror di SF" rel="external noopener">Sourceforge</a>.
</p>
<p>
Thanks to <a href="http://slackware.ponce.cc/blog/" title="Vai al sito di Ponce" target="_blank" rel="external noopener">Ponce</a> for the hosting.
</p>
</section>

<footer>
<p>
Slackware is a Registered Trademark of Slackware Linux, Inc.
<br>
Linux is a Registered Trademark of Linus Torvalds.
<br>
<a href="privacy.php" title="Privacy Policy" class="privacy">Privacy Policy</a>
</p>
</footer>
<div class="supportme">
<a href="https://paypal.me/conraid" title="Sostieni questo repository">
<i>Support</i><i>Me</i>
</a>
</div>
<script defer type="text/javascript">
var speed = document.createElement('link');
speed.rel = 'stylesheet';
speed.href = 'css/slackers.min.css';
speed.type = 'text/css';
var defer = document.getElementsByTagName('link')[0];
defer.parentNode.insertBefore(speed, defer);
</script>
<noscript>
<link rel="stylesheet" type="text/css" href="css/slackers.min.css">
</noscript>

</body>
</html>